### ISSUE TITLE
Typo in Finnish localization file

### ISSUE THREAD

**Issue by Kallio** [CSCfi/swift-browser-ui#1054]
#### To Reproduce
Steps to reproduce the behaviour:
1. Go to ['config/.finniswords.txt'](https://github.com/CSCfi/swift-browser-ui/blob/204642138ea10628a2c6f1ec655ee38b5db0c252/.github/config/.finnishwords.txt)
3. Replace word Halutako = Haluatko
4. Commit
5. Push to production

**Comment by plaihonen** [comment]
![image](https://user-images.githubusercontent.com/10773070/234252695-22c16f8a-a836-4d6d-8969-83a6e04407ba.png)
In the above dialog, "cancel" should be replaced with the Finnish equivalent to keep language consistent.
