### ISSUE TITLE
Why a python middleware?

### ISSUE THREAD

**Issue by drzraf** [CSCfi/swift-browser-ui#108]
This project is one of the very few that support keystone v3 and (the even fewer) maintained to date.

I didn't understand well the scope and goals of the project and I've a couple of questions about the server-side technical choice.

According to the description:
> A web frontend for browsing and downloading objects saved in SWIFT compliant object storage, supporting SSO with SAML2 federated authentication.

Why should the frontend needs to proxy requests though a Python intermediary server?
- **CORS**? Swift [supports CORS settings](https://docs.openstack.org/swift/latest/cors.html). No Javascript limitation here.
- Could it be that users must not access **Keystone user/password**? Then wrapping only the `/v3/auth/tokens` could also be enough (then subsequent requests could be issued directly to upstream Swift endpoint using that token which is time-limited)?
- Cost of **protocol implementation**? The backend makes use of Python swiftclient to handle Swift protocol. But there are some pure-javascript client implementation out there. Some [cross-platform](https://github.com/pkgcloud/pkgcloud) object-storage npm libraries even exist so that client-code supports Swift, Azure or S3...

On the opposite I'd see a lot of advantages into plugging directly a JS view (Vue/React) into the Swift-endpoint but, quite strangely, have found very little software for that purpose:
- https://github.com/mgeisler/swift-browser (unmaintained, Keystone v2.0 only)
- https://github.com/fanatic/swift-ui (unmaintained, to be installed on a public Swift bucket rather than a truly local UI)

Why?

**Comment by blankdots** [comment]
@drzraf Thank you for your interest in the project.
Your points make perfect sense and we thought about going with full front-end technologies. 
One good place to start understanding the technologies choices we made come for the requirements section:
> an account that has access rights to **CSC Pouta platform**, and is taking part to at least one project as object storage is project specific.

This means we designed the solution to be suitable to the deployment of Openstack we are working with, and we are seeking to add some functionality of our own through multiple services, that we think it is easier to orchestrate via a python middleware. For this requirement we needed to think beyond just having a pure front-end implementation.

Second reason is historical, as this project was at the beginning designed to be an API which got shortly after an simple UI then a more sophisticated one.

Hope this addresses your concerns and thank you again for the interest.

**Comment by drzraf** [comment]
Understood. Thank you for the explanation.

Maybe the best place I should look for is in the [horizon objects manager](https://github.com/openstack/horizon/blob/master/openstack_dashboard/dashboards/project/static/dashboard/project/containers/objects.controller.js).
