### ISSUE TITLE
Project sharing support on the browser platform

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#25]
#### Proposed solution
~~Access Control List support needs to be validated as working, so that the user projects can be granted access to other projects' containers via the tools readily provided by Openstack. This would allow e.g. using single project for uploading multiple users' files, which is somewhat required from the platform currently~~.

**UPDATE:** ACLs won't work as required, since the container still wont work like a container natively created in the project, regardless of the amount of rights given in the ACL. (this is now validated) This means a different approach needs to be chosen.

#### DoD (Definition of Done)
There is a way to share projects between users in a way that reflects on the browser UI.

#### Testing
Visual inspection and validation of the required functionality, new tests shouldn't be required.

**Comment by sampsapenna** [comment]
### Chosen approach
Implement an access control backend in a different project.

**Comment by sampsapenna** [comment]
### Chosen approach
Implement an access control backend in a different project.

**Comment by blankdots** [comment]
I think it should be closed, if necessary we will open issues on the new repo.
