### ISSUE TITLE
implement paging in API requests

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#259]
#### Proposed solution

Large requests in the backend API should execute quicker, since it can often take > minute for a large request to go through. This is due to large requests being pooled together in the backend, instead of the frontend – a behavior which could be improved upon by proxying paged requests and parsing them into a complete one in the frontend instead.

#### DoD (Definition of Done)

Paged requests are used in optimizing the container and object listings in the application.

#### Testing

New unit tests need to be written to reflect this functionality, which differs from the current implementation somewhat.

**Comment by sampsapenna** [comment]
Page API requests would require stitching the whole requests together somewhere, currently this task is done in the backend but moving it to frontend would be beneficial for performance reasons already. The paging support and quicker user response is an additional benefit, but not the only one. The long response times for large requests have lead to the misunderstanding that the UI with its backend can't handle listing containers with hundreds of thousands of objects, which it can do without issues.

**Comment by csc-felipe** [comment]
https://docs.openstack.org/swift/latest/api/pagination.html
