### ISSUE TITLE
support encryption for uploaded objects

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#262]
#### Proposed solution

Supporting encryption for objects upon upload will be a necessary feature for the userbase. This should probably be implemented with WASM to enable faster performance for processing the objects during encryption.

#### DoD (Definition of Done)

Encrypted objects can be uploaded using the UI, without encrypting them beforehand.

#### Testing

Frontend tests can be added for validating this behavior.

**Comment by sampsapenna** [comment]
Go wasm implementation currently only supports filesystem operations on node.js. Need to either:
* directly stream the files from html5 file API without emscripten FSAPI, perform the encryption and stream files back (inconvenient)
* write a crypt4gh implementation from scratch with C or C++
* patching WASM FSA API support to Go if not yet present in some other project (most convenient if possible)
* possibly moving over to using Rust, since rust has WASM FSA API support available

**Comment by sampsapenna** [comment]
Can't use [FSA API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility) due to compatibility issues. It's supported well on chrome and edge, but lacking support for firefox which will cause issues.

**Comment by juhtornr** [comment]
There is Crypt4GH implementation in C: https://github.com/silverdaz/crypt4gh

**Comment by sampsapenna** [comment]
Crypt4gh C implementation builds with WASM as the target have been tested, automatized and feel stable. There is a demoable implementation of the encryption pipeline for the UI. The actual implementation will be merged after a bit of UI polish.
