### ISSUE TITLE
Deleting the last bucket does not refresh the browser view

### ISSUE THREAD

**Issue by jaakkocsc** [CSCfi/swift-browser-ui#356]
#### Describe the bug
If you delete the last bucket in the project a notification is shown that the bucket is deleted, but the view does not get updated and the bucket is still visible and you can still open the bucket.

#### To Reproduce
Steps to reproduce the behaviour:
1. Select a project with one bucket (or one without any and create a new bucket).
2. Select the bucket and click "Delete".
3. A notification pops up saying bucket was deleted.
4. The bucket is still visible the browser and is still accessible, you can click "Delete" again and you can even open the bucket.

#### Expected behavior
Along with the notification in step 3 above, the browser view should be refreshed so that the bucket disappears.

#### Screenshots
![image](https://user-images.githubusercontent.com/10267750/137113134-65433be8-0810-4da0-be9f-1752998a71c1.png)

#### Additional context
Tested with latest Firefox (93.0 for macOS).

**Comment by sampsapenna** [comment]
Most likely has to do with JS side error handling ditching error requests – 404 should either be rendered as an empty table upon update or be caught, in case it's visible to the JS side as a CORS error instead of a 404 as has been the case previously
