### ISSUE TITLE
Download data encrypted with user's key

### ISSUE THREAD

**Issue by blankdots** [CSCfi/swift-browser-ui#379]
#### Description

As a researcher I need to be able to download encrypted data that i can use in my research.

Data in SD-Connect is encrypted with services public key and we need to be able to add the researcher's public key for them to be able to download the data and use the data.

We might need a mechanism to obtain the researchers public key.
Note: this service might need the private key to decrypt the header so it can add a new public key.

**If our public key has been added to recipients, we will support downloading as is:**, without the need for user's private key.

#### DoD (Definition of Done)

Researcher can download encrypted data and they can open it.

#### Testing

Peer review, Unit and Integration testing

**Comment by sampsapenna** [comment]
Closing issue for now, moving tracking of the functionality to https://github.com/CSCfi/swift-browser-ui/issues/576 since it better reflects the new issue format.
