### ISSUE TITLE
Support encryption for objects – continued with proper UI integration

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#380]
#### Proposed solution

The working encryption interface needs to be interfaced with the UI in a proper manner. The encrypted upload process needs to be available via the ordinary UI that an end user will use, so it will need navigation items pointing to it etc.

#### DoD (Definition of Done)

There exists an encrypted upload implementation in the UI, that the users can navigate to without knowing the direct address for the view.

#### Testing

Visual testing of the functionality, maybe feedback from the customer support eventually.

**Comment by blankdots** [comment]
continuation of #262
