### ISSUE TITLE
Consistency in terminology

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/swift-browser-ui#428]
#### Proposed solution
We use the words _container_ and _bucket_ interchangeably. This can be confusing.

#### DoD (Definition of Done)
Unify the use of the terminology in the code, ui, api and docs.

#### Testing

peer-review and `grep`.

**Comment by sampsapenna** [comment]
IMO container in backend/API development and documentation to preserve parity with Openstack – bucket in the frontend to not confuse the end user
