### ISSUE TITLE
Frontend tests for encryption

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#463]
#### Proposed solution

Changes made to the frontend to add encryption supports aren't covered by the cypress tests. These tests should be added. Testing the ordinary upload functionality could be added at the same time as well.

#### DoD (Definition of Done)

Frontend changes related to encrypted uploads are tested with cypress.

**Comment by csc-felipe** [comment]
Just found this about file uploads https://github.com/cypress-io/cypress/issues/170

https://cypress.io/blog/2022/01/18/uploading-files-with-selectfile/

**Comment by blankdots** [comment]
> The [.selectFile()](https://docs.cypress.io/api/commands/selectfile) command replaces the cypress-file-upload community plugin by [Paul Auramenka](https://github.com/abramenal),

we have been using that plugin in metadata-submitter front-end, good to know we can replace it

**Comment by csc-felipe** [comment]
Tracking somewhere else
