### ISSUE TITLE
Drag-n-drop file listing state is not synced to upload view

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#465]
#### Describe the bug

Dropped files repopulate into the upload view file listing after deletion, if new files are added via drag-n-drop.

#### To Reproduce
Steps to reproduce the behaviour:
1. select upload
2. drag-and-drop a file to the page
3. remove it from the list. List will be empty
4. drag-and-drop another file to the page
5. both files are on the list, also the previously removed one
If the second file is the same as the first one, it is twice on the list.

#### Expected behavior

File removals from the UI are synced to the vuex and do not repopulate into the index.

#### Additional context

This is a Firefox only bug.

**Comment by juhtornr** [comment]
I experience this also with Safari and Chrome.
