### ISSUE TITLE
Support project isolation for token

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#468]
#### Proposed solution

There should be a possibility to limit project scope when necessary. Some services will require this due to regulation.

#### DoD (Definition of Done)

Project scoping can be configured to limit scope to a single project per session, when necessary.

#### Testing

UI tests can be written if necessary.

**Comment by sampsapenna** [comment]
We will need some sort of an endpoint for checking if a project taints the session. A tainted session will not be allowed to change project scoping after initial login, but will need to begin the login process again in case they want to change the scope.

**Comment by juhtornr** [comment]
Project isolation will disable sharing functionality.
