### ISSUE TITLE
Able to read from a wite only shared bucket

### ISSUE THREAD

**Issue by vvaltia** [CSCfi/swift-browser-ui#472]
#### Describe the bug
A bucket is shared with write only permissions. After writing a file into the bucket, it can be read.

#### To Reproduce
1. Share a bucket with an other user with write only permissions
2. The other user writes a file to the bucket
`curl -X PUT -H "<<authentication_header>>" -T "testfile" https://<<url>>/<<shared_write_only_bucket>>/testfile`
3. The other user is able to read the file
`curl -X GET -H "<<authentication_header>>" https://<<url>>/<<shared_write_only_bucket>>/testfile`

#### Expected behavior
The other user is not able to read the file

**Comment by sampsapenna** [comment]
I inspected the `X-Container-Write` header the UI creates for write access. There is nothing wrong in the ACLs, but at least in our environment setting the write rights will allow reading as well. According to [ceph documentation](https://docs.ceph.com/en/pacific/radosgw/swift/containerops/#update-a-container-s-acls) this should not be the case.

**Comment by blankdots** [comment]
if this is not a `swift-browser-ui` issue, we should close this.
