### ISSUE TITLE
Cannot read object uploaded with write only rights

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/swift-browser-ui#475]
#### Describe the bug
Even though it is possible to upload into a shared container with write-only rights, the owner cannot download (read) those objects.

#### To Reproduce
Steps to reproduce the behaviour:
1. Share a container with write only rights
2. The account with the write-only rights uploads a file
3. Owner downloads file
4. See permission denied error

#### Expected behavior
The owner should be able to read the files.

#### Additional context
This is a follow-up from #472.

**Comment by sampsapenna** [comment]
Closing as an external bug, probably related to the Ceph RGW. This behavior can be observed when using command line tools as well.

Reading objects after writing to a write only bucket is a discrepancy for both Swift and S3 ACLs, at least in regard to RedHat's docs for Ceph Object Storage. The bucket owner not being able to access the uploaded files is a discrepancy as well.

https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/1.3/html/object_gateway_guide_for_ubuntu/object_gateway_s3_api#access_control_lists_acls
https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/1.3/html/object_gateway_guide_for_ubuntu/object_gateway_swift_api#update_a_container_s_acls

**Comment by csc-felipe** [comment]
Let's disable write-only while no other solution is possible.
