### ISSUE TITLE
Enable option to show hidden files

### ISSUE THREAD

**Issue by blankdots** [CSCfi/swift-browser-ui#478]
#### Description

With https://github.com/CSCfi/swift-browser-ui/pull/442 we hide segment of the files, however we need to display them.

#### DoD (Definition of Done)

toggle button available to show hidden files.

#### Testing

Unit and Cypress tests

**Comment by csc-felipe** [comment]
I wonder where in the UI this would go. I think we should wait until we have better ui to add such functionality.
