### ISSUE TITLE
Drag and drop does not work in new upload view

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#495]
#### Describe the bug

When I drag and drop files (or directories) to the new upload view (developed in #479) "Encrypt and upload" button stays disabled. Everything works as expect if I manually choose files using "Select files for upload" button. 

#### To Reproduce
Steps to reproduce the behaviour:
1. In "Browser" view click "Upload" button
2. Drag and drop files to the browser window
3. See that "Encrypt and upload" button stays disabled

#### Expected behavior

I would expect that after drag and drop "Encrypt and upload" button would became enabled and you could perform the upload. 

#### Screenshots

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/396559/153000424-467488a5-0765-4853-bf28-7f2fe93cc1a0.png">

**Comment by juhtornr** [comment]
This seems to be duplicate to #465.

**Comment by juhtornr** [comment]
Duplicate of #465

**Comment by blankdots** [comment]
> Duplicate of #465

it appears it is not a duplicate maybe it is related to #494
