### ISSUE TITLE
Clear items to upload on the upload UI

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/swift-browser-ui#499]
#### Proposed solution
The only way to remove items from the upload list, is to click one by one on the remove button. Closing the upload page by navigating away does not clear the items, which is ok (perhaps even a feature), but there should be some way to clear the list more easily.

#### DoD (Definition of Done)
- Add a clear or cancel button that removes items from upload list. A clear button would only clear the list, while a cancel button would clear the list and "close" the upload view.

**Comment by blankdots** [comment]
>  Closing the upload page by navigating away does not clear the items, which is ok (perhaps even a feature) 

yes, it is by design
