### ISSUE TITLE
Expose metadata to user

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#5]
#### Proposed solution
The user needs to be able to see the meta-data contained within the object storage, as this data often has significance to the datasets' usage. The actual contents of the meta-data aren't important, everything should be possible to be at least shown, and hopefully filtered. (in the future) The data could probably be shown in an easy-to-read format under the details expansion in the tables.

#### DoD (Definition of Done)
Meta-data can be read and hopefully used in filtering the objects that are shown to the user.

#### Testing
Unit tests for the new API functionality required for the meta-data, UI tests for its correct rendering.

**Comment by sampsapenna** [comment]
* Update on 2020-01-21; implemented in the back-end, front-end waiting for a use case for the metadata

**Comment by blankdots** [comment]
we need to be able to get actual project size not have it at default 1TiB

**Comment by blankdots** [comment]
we can display them as part of details of the object
![image](https://user-images.githubusercontent.com/47524/145971570-3746831f-a4b4-4caa-bb22-c7ce7932dc27.png)

This is a task only about displaying metadata, if it exists.
