### ISSUE TITLE
Upload UI: Selecting files button works only once

### ISSUE THREAD

**Issue by csc-felipe** [CSCfi/swift-browser-ui#500]
#### Describe the bug
Selecting files with the button works only the first time. A person cannot select files from different locations for the upload.

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to upload page
2. Click on "Select files to upload"
3. Select some files, and click OK
4. Click on "Select files to upload"
5. Select some files, and click OK
6. Notice that new files were not added

#### Expected behavior
Selecting files should always add them.

**Comment by blankdots** [comment]
replicated, will try to see where the issue is.
