### ISSUE TITLE
Skip second login button click when using Haka as first login step

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#565]
#### Proposed solution

At the moment, when user logs in with HAKA he/she is redirected to another login page where he/she needs to press login button again. This step can be skipped with utilising existing HAKA login session.

**Comment by csc-felipe** [comment]
This can be done when we have the Haka claim from SDS AAI (OIDC provider).

**Comment by csc-felipe** [comment]
@juhtornr, this is actually a backend change.
