### ISSUE TITLE
As a researcher, I want to upload files up to 100GBs so that I can store my large files in the service 

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#575]
#### Describe the user story

At the moment it is possible to upload and encrypt only files up to 1GB to the service. This limit should be extended to 100 GBs.

#### Tasks:
- [ ] https://github.com/CSCfi/swift-browser-ui/issues/399

#### Testing 
Create a test case that uploads a 100 GB file to the service.

#### Definition of Done
Given large file when I do upload it then I expect get it stored to the service

**Comment by blankdots** [comment]
could this formulated as a `need`, because having phrased as a `want`, makes it a nice to have or it is up to debate if we should even consider implementing it.
