### ISSUE TITLE
As a researcher, I want to have clear navigation view in SD Connect that I can find the features available in the service

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#577]
### Design:

https://www.figma.com/file/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=517%3A2533

### User stories:
- [x] #596
- [x] #597
- [x] #611
- [x] #612
- [x] #613
- [x] #715 
- [ ] #706 
- [ ] #648 
- [x] #701 
- [x] #702 
- [x] #716

### Tasks:

- [x] Update top bar visuals (Logo, User information)
- [x] Add language selection

**Comment by csc-felipe** [comment]
The title is not self-evident. It would be nice to have more context. It sounds like there are pain points behind this, and it's not obvious what they are. Perhaps the user story goes more like: "As a researcher, I feel confused with .... and I cannot find ...."

**Comment by csc-felipe** [comment]
The title is not self-evident. It would be nice to have more context. It sounds like there are pain points behind this, and it's not obvious what they are. Perhaps the user story goes more like: "As a researcher, I feel confused with .... and I cannot find ...."

**Comment by blankdots** [comment]
also could this formulated as a `need`, because having phrased as a `want`, makes it a nice to have or it is up to debate if we should even consider implementing it.
