### ISSUE TITLE
As a researcher, I want to browse my folders in simplified view that I can find key features easily

### ISSUE THREAD

**Issue by juhtornr** [CSCfi/swift-browser-ui#578]
- [x] #638
- [x] #639
- [x] #640
- [x] #641
- [x] #642
- [x] #643
- [x] #645
- [x] #649
- [x] #695
- [x] #703 
- [x] #724 
- [x] #725 
- [ ] #726 
- [x] #728 
- [x] #738 
- [x] #739 
- [x] #717 
- [x] #729

**Comment by csc-felipe** [comment]
The story could use some context. From "can find key features easily", it sounds that right now "key features" cannot be found easily, but there's no information on which ones, or what the researcher considers "key features".

**Comment by csc-felipe** [comment]
The story could use some context. From "can find key features easily", it sounds that right now "key features" cannot be found easily, but there's no information on which ones, or what the researcher considers "key features".

**Comment by blankdots** [comment]
also could this formulated as a `need`, because having phrased as a `want`, makes it a nice to have or it is up to debate if we should even consider implementing it.

**Comment by blankdots** [comment]
let us close this even though one task still remains, this can be handled separately
