### ISSUE TITLE
Shared bucket does not show number of files

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#608]
#### Describe the bug

SD Connect shared bucket does not show number of files (problematic from FIMM, they don't know how many files they uploaded to the bucket shared with them by the researchers). 2TB transferred successfully from FIMM to iCAN.

#### To Reproduce
Steps to reproduce the behaviour:

**Comment by fmorelloCSC** [comment]
![image](https://user-images.githubusercontent.com/83574067/169503939-198a98dd-e02d-4b62-aa28-bec8741aaaec.png)

**Comment by fmorelloCSC** [comment]
In this example Kimmo (the researcher) shared a bucket with me (sequencing facility). If I click on the bucket I can see its content and upload files. But when I look at the bucket from the view, I don't know if the total number of files changed.
