### ISSUE TITLE
Hot-reload in Node.js environment

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/swift-browser-ui#635]
#### Describe the bug
Hot-reload doesn't work as supposed when serving frontend via NPM commands.

#### To Reproduce
Steps to reproduce the behaviour:
1. Follow Development -instructions described in README.md in "devel" branch
2. Serve app with `honcho start`
3. Go to `http://localhost:8081/badrequest` route
3. Edit `pages/IndexPage.vue` component
4. See error in console

#### Expected behavior
Hot reload reloads on change and doesn't error.

#### Screenshots

![image](https://user-images.githubusercontent.com/48789543/172108573-5cf278cd-4e4b-4bde-9b40-1776f185d7e3.png)

#### Mentions
Problem doesn't happen if `<script>` tags and its content is removed.
This problem seems to be related to entries and related components that handle Vue instances props in both files.

**Comment by saulipurhonen** [comment]
I suggest that we'll leave this to backlog and evaluate later since App creation template and Vue 3 upgrade (mentioned in https://github.com/CSCfi/swift-browser-ui/pull/614) is planned and these would change current behavior drastically and therefore introduce a possible fix for this problem.

**Comment by ainoc** [comment]
This doesn't concern user.
