### ISSUE TITLE
Write development documentation

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#64]
#### Description

The tools used in development, and some of the decisions taken should be documented more thoroughly.

#### DoD (Definition of Done)

The necessary documentation exists.

#### Testing

Proofreading

**Comment by blankdots** [comment]
Related to this: https://github.com/CSCfi/swift-ui-deployment/pull/3

**Comment by blankdots** [comment]
Current status is satisfiable to close the issue
