### ISSUE TITLE
Display options for folders list

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#640]
Menu to toggle tags and pagination on/off

**Comment by hannyle** [comment]
This feature still needs a new UI design in figma.

**Comment by ainoc** [comment]
![Screenshot 2022-08-01 at 11 12 25](https://user-images.githubusercontent.com/101800110/182103819-1adb970a-c4c6-4dda-a74f-d32a7a26ecd5.png)

Here is a screenshot of this dropdown.
