### ISSUE TITLE
Options for folder

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#645]
Folder options (dropdown menu): Edit tags, Delete

**Comment by saulipurhonen** [comment]
@ainoc, in current implementation "copy" button can be disabled depending on value of folder bytes. CSC DS [Menu component](https://csc-design-system-docs.web.app/c-menu) doesn't allow styling of menu items and this means that we're not able to disable menu item when certain criteria is met.

I think it's wise to not allow user to try copy folders which meet this criteria. 

One option is to remove "copy" item from menu when it should be disabled but I think this could confuse some users.

If we'd like to display disabled menu item eg. as greyed out and without functionality I think minimum we'd need from design system would be to be able to add a custom css class for menu items.

**Comment by ainoc** [comment]
I've asked for changes from DS devs.
