### ISSUE TITLE
Upload notification

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#648]
Given that user has started upload
when user will see notification of upload process with progress bar, text "Upload has started, this might take few minutes." and link to destination folder
then user can select View destination folder link in notification
and then user will see folder where files are being uploaded.

**Comment by sampsapenna** [comment]
There are multiple values in `store.js`

Current one used is `uploadProgress`, that's used for tracking unencrypted uploads

For encrypted uploads there are:
* `encryptedFile` which displays the file currently in progress
* `encryptedFileProgress` which displays progress in currently uploaded file
* `encryptedProgress` which is the total progress of an encrypted upload, out of multiple files

Difference between the two can be used to infer which type of upload is currently happening.

**Comment by ainoc** [comment]
Multi-line text field for public keys needs to be added.
