### ISSUE TITLE
Datatable (All folders)

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#649]
List of folders in a project: https://www.figma.com/file/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=517%3A2533

Related issues:
- [x] #738
- [x] #739

**Comment by ainoc** [comment]
Items column to be added. Figma file has been updated.

**Comment by ainoc** [comment]
Change color of folder names from blue to csc dark grey.

**Comment by saulipurhonen** [comment]
> Change color of folder names from blue to csc dark grey.

CSC DS link-component doesn't allow different colored links. I've made a suggestion and it's now waiting for approval.

**Comment by saulipurhonen** [comment]
This implementation is also waiting another approval from DS-team regarding "c-menu" component. Current version doesn't allow "options" menu to be rendered as in layout prototype.

PR for suggestion: https://github.com/CSCfi/csc-ui/pull/40

**Comment by ainoc** [comment]
Shared status column has been modified. Column should display You have shared / Shared with you.
