### ISSUE TITLE
Footer redesign

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#694]
Implement new footer design: https://www.figma.com/file/N0Y3N0nfyMS2wG3gjwZ201/SD-Connect-Prototype?node-id=517%3A2533

Links (open in new tab):

Service description: https://research.csc.fi/-/sd-connect

**Comment by ainoc** [comment]
Text fixes:

SD Connect – Sensitiivisen datan palvelut / SD Connect - Services for Sensitive Data

CSC – Tieteen tietotekniikan keskus Oy / CSC - IT Center for Science Ltd.

**Comment by ainoc** [comment]
Link hover styles missing?

**Comment by csc-felipe** [comment]
Texts need to be updated, and links are not opening in a new tab. In the future, it would be better to request changes before the PR is merged, or then to create a new issue with the new requests.
