### ISSUE TITLE
Top navigation links disappear on smaller screens size

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#696]
#### Describe the bug
When browser window width is less than less than 1024 px, links in top bar disappear.

#### To Reproduce
Adjust  browser window width to less than 1024 px.

#### Expected behavior
Top bar links are visible and adjust responsively to width of browser window.

**Comment by ainoc** [comment]
Duplicate.

**Comment by csc-felipe** [comment]
> Duplicate.

It's a good practice to link to the duplicate. I can't find what is this a duplicate of, closing.
