### ISSUE TITLE
Reloading upload route breaks logic

### ISSUE THREAD

**Issue by saulipurhonen** [CSCfi/swift-browser-ui#699]
#### Describe the bug

App logic breaks when reloading upload route. This happens in current implementation where upload -modal hasn't been merged yet.

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to `Upload` page `/browse/upload/{projectId}/{uploadId}`
2. Refresh page
3. Navigation items do not line up as those should, Create folder -button doesn't do anything and uploading a file reloads some old version of `UploadProgressBar` component.

#### Expected behavior
All logic should work on reload as it works when navigation from default browser view.

#### Screenshots

![image](https://user-images.githubusercontent.com/48789543/184593077-26439482-3337-4249-94d7-0bead4e280eb.png)

#### Additional context

Top navigation css problem looks like styles "bleed" from IndexPage, IndexOIDCPage or LoginPassoword pages. Inspector shows a  style that is declared only in previously stated pages.
```
c-button {
    margin-top: 2rem;
}
```

**Comment by ainoc** [comment]
Let's wait for upload merge.

**Comment by hannyle** [comment]
Close this issue as it hasn't been seen again with the new Upload modal and for other routes.
