### ISSUE TITLE
Folder structure is lost in shared view after upload

### ISSUE THREAD

**Issue by fmorelloCSC** [CSCfi/swift-browser-ui#704]
This issue is common to most of our users, but especially important to solve for users that have thousands of objects (e.g. 20.000).
 When someone uploads data to the shared folder, the user that can see the shared content would like to know if all the files are there, or if something happened during the upload.
In this case, it is important to see folder structures, each folder's size, and the number of objects in it. However, in the shared folder the structure is lost and the UI is rendering the same root folder 20000 times if there are 20000 objects.

shared folder:

![Image](https://user-images.githubusercontent.com/83574067/185104030-a6e2df9a-104e-4fe4-a5df-66c49872d617.png)

There is just one DATA folder and one script folder in it:
![Image](https://user-images.githubusercontent.com/83574067/185104077-325d784b-64be-4bba-bd85-ab6fc4b989c2.png)

But the data folder is rendered 9 times and I can not see the structure anymore:
![Image](https://user-images.githubusercontent.com/83574067/185104150-e69c5ca7-d2be-4096-b885-3c8e71ad0124.png)

@ainoc

**Comment by juhtornr** [comment]
This is part of the download PR. If not then @sampsapenna will create a follow-up PR.
