### ISSUE TITLE
Not possible to upload new data to a folder in SD Connect

### ISSUE THREAD

**Issue by fmorelloCSC** [CSCfi/swift-browser-ui#705]
I shared bucket "2001659-some-genomes " with development project some days ago. This bucket contains genomes of different organisms in pseudodirectory:

2001659-some-genomes/genomeja.

Now if any user would like to add a new genome to this pseudofolder, it is not possible with SD Connect, because the upload process always adds "data/" pseudofolder to the beginning of the object name.
Like: 2001659-some-genomes/data/genomeja/dog-genome.fasta

This issue is connected to the way in which we manage segments (creating a DATA folder). 

for questions contact Kimmo

@ainoc

**Comment by juhtornr** [comment]
Pseudo folder issues will be fixed in existing PR.
