### ISSUE TITLE
IndexedDB flakiness with container listing updates

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#778]
#### Describe the bug

When container listing is updated, old entries are not patched. This leads to new entries being added and then removed, instead of old entries being updated and stale ones being removed.

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to browser navigation page
2. Open a container
3. Delete some objects inside the container
4. Perform a cache-less refresh of the webpage
5. See the object and byte count for said container not updating

#### Expected behavior

Refresh updates the container/folder content information

#### Additional context

This is probably due to incorrect fetches with the IndexedDB after async API updates.

**Comment by ainoc** [comment]
Related to https://github.com/CSCfi/swift-browser-ui/issues/743

**Comment by sampsapenna** [comment]
Related to #752
