### ISSUE TITLE
Copy folder modal fixes

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#799]
![Image](https://user-images.githubusercontent.com/101800110/199924644-bb689e3a-31bd-4076-86e1-0b7c52bb00fa.png)

**Comment by ainoc** [comment]
Is this done? @hannyle

**Comment by hannyle** [comment]
@ainoc Yes, it is Done and already merged to `devel` branch. But I could see that it is not in the sd-connect test page yet.

**Comment by hannyle** [comment]
@ainoc There are some conflicts when merging branches, I pushed the fix to this PR: https://github.com/CSCfi/swift-browser-ui/pull/884
It will be merged to `devel` branch and deployed to sd-connect test page hopefully soon :)

**Comment by csc-felipe** [comment]
@ainoc, could you confirm this is fixed and close the issue or comment here?
