### ISSUE TITLE
Add header backup call for keyswap and test backup and restore

### ISSUE THREAD

**Issue by sampsapenna** [CSCfi/swift-browser-ui#802]
#### Proposed solution

Currently backup and restore is only working properly for the key policies. Whitelist and file headers need to be possible to back up as well.

#### DoD (Definition of Done)

Backup and restore works for all relevant entries of the key swapping Vault plugin.

#### Testing

Verification by hand for now, unit tests and integration tests to be added in the future.

**Comment by csc-felipe** [comment]
Should be part of the plugin tests
