### ISSUE TITLE
Modals / Add minimun width and height

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#816]
Same styling of Upload modal added to:

- Edit tags modal
- Share modal
- Copy modal

**Comment by hannyle** [comment]
@ainoc Could you tell more about this issue? What styles do we need ?

**Comment by ainoc** [comment]
Modals should have same width and height as Upload modal

**Comment by hannyle** [comment]
Upload modal is way bigger than other modals because of its large content. 
Having other modals up to the Upload modal 's size seems not a good solution to me tbh.
