### ISSUE TITLE
Too long folder name breaks datatable row

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#860]
Possibly too long folder name causes:

![Image](https://user-images.githubusercontent.com/101800110/202415274-5f9cf1c4-dc3b-4150-beea-2e042b59e04c.png)

**Comment by rquazi** [comment]
I have tried with long names to reproduce the issue. Is there any particular steps to reproduce?

**Comment by rquazi** [comment]
Already fixed in the current data table
