### ISSUE TITLE
Render as folders 

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#869]
#### Describe the bug
When user selects Render as folders it doesn't work as intended.

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to front page.
2. Click on Display options -> Render folders
4. Files inside folder aren't rendered as folders. 

#### Expected behavior
When user selects Render folders, files should be displayed as in folders according to folder structure that was in place when a folder with nested folders was uploaded by the user.

**Comment by juhtornr** [comment]
@sampsapenna is planning to start working on this week (Tue/Wed).
