### ISSUE TITLE
Copy Share ID / Tooltip under tabs

### ISSUE THREAD

**Issue by ainoc** [CSCfi/swift-browser-ui#909]
#### Describe the bug
When tooltip is activated through icon, it is underneath All folders and Folders you have shared tabs (tested in Chrome browser).

#### To Reproduce
Steps to reproduce the behaviour:
1. Go to SD Connect test version.
2. Click on icon next to Cope Share ID button.
3. Tooltip is underneath tab.

#### Expected behavior
Tooltip should be over tabs.

#### Screenshots

![Image](https://user-images.githubusercontent.com/101800110/210348328-aa4eef6a-3d83-4f9b-a3ad-179150ca4c7a.png)

**Comment by juhtornr** [comment]
This is solved and can be closed.
